apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: filebeat
  labels:
    app: filebeat
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - events
    verbs:
      - get
      - watch
      - list
