apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
      - add_host_metadata: ~
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
